version: '3'
services:
  windnode_scenario_db:
    image: postgres:12-postgis
    container_name: windnode_scenario_db
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.postgis
    ports:
    - "127.0.0.1:54321:5432"
    environment:
      POSTGRES_DB: windnode_abw
      POSTGRES_USER: windnode
      POSTGRES_PASSWORD: windnode
    volumes:
    - $HOME/docker/volumes/postgres/windnode_abw:/var/lib/postgresql/data
    - ./entrypoints:/docker-entrypoint-initdb.d/
